### ISSUE TITLE
"Press enter to terminate" message is confusing

### ISSUE THREAD

**Issue by IvanSanchez** [NordicSemiconductor/pc-nrfutil#105]
Performing a Thread DFU will print a `Press <ENTER> to terminate` message...

https://github.com/NordicSemiconductor/pc-nrfutil/blob/202fc2850deadfb8dbf40460f53f75033673b8cb/nordicsemi/__main__.py#L913

...while the NCP is trying to be promoted to a router, but from a naïve user point of view, what I got is:

```
C:\Users\....\pc-nrfutil>nrfutil dfu thread -pkg ...\app_dfu_package.zip -p COM10
Address not specified. Using ff03::1 (all Thread nodes)
Using connectivity board at serial port: COM10
Press <ENTER> to terminate
```

i.e. as a user, my first reaction is to think "this has finished successfully without error, and is asking me to press enter to end". This is not the case.

If a thread DFU procedure is going to print messages in non-verbose mode, please make those messages be more informative. e.g. `Attempting to promote NCP to router status, press <ENTER> to cancel`.

Also:
- Please use `Ctrl`+`C` as the key combination to press when wanting to cancel stuff
- Please use `enter` as the key to press when confirming something or accept a default action

**Comment by rlubos** [comment]
I agree that feedback from the nrfutil could be more descriptive in this case. I will update it and use `CTRL` + `C` to stop the server.
