### ISSUE TITLE
Temporary files are not cleaned up

### ISSUE THREAD

**Issue by IvanSanchez** [NordicSemiconductor/pc-nrfutil#110]
After running some tests with some automated `nrfutil pkg generate ...`, this is how my `/tmp` directory looks like:

![image](https://user-images.githubusercontent.com/1125786/32835882-194fa450-ca08-11e7-85eb-8d7fe80d15fa.png)

It appears that temporary files are not cleaned up when finished. More investigation is needed.

**Comment by halkver** [comment]
Can't reproduce. Probably fixed.
