### ISSUE TITLE
how generate zip file with legacy version(0.5.2)

### ISSUE THREAD

**Issue by fkeujjpdc** [NordicSemiconductor/pc-nrfutil#113]
hello:
i wan't convert hex file to zip file without key-file . but i use "pip install  nfrutil" download new version(1.5.0)
that it must use pem file . how can i generate zip file without key-file.

**Comment by ArthurHCL** [comment]
I also want to know the issue,for help......

**Comment by svenKautlenbach** [comment]
checkout branch 0_5_3 or by tag v0.5.3 that has the legacy support

**Comment by bihanssen** [comment]
The response of @svenKautlenbach is correct, you can check out the branch or tag and build from there.

In theory it should be possible to install nrfutil 0.5.3 with pip, with the command `pip install nrfutil==0.5.3`, though I'm having problems that seem to be related to incompatiblilties between pip versions.
