### ISSUE TITLE
In case of SD+BL+APP update: SD+BL takes more time to finish and new BL can boot-up. Need to add time delay in dfu serial open

### ISSUE THREAD

**Issue by qung** [NordicSemiconductor/pc-nrfutil#126]
>def open(self):
>>        time.sleep(7)
>>        super(DfuTransportSerial, self).open()

**Comment by bihanssen** [comment]
Hi, thanks for reporting. 
Would you mind creating a pull request for your suggested change?

**Comment by mrodem** [comment]
Fixed by introducing an optional `--connect-delay <second>` parameter in #129.
