### ISSUE TITLE
Is pc-ble-driver 3.x going to be supported?

### ISSUE THREAD

**Issue by LJBD** [NordicSemiconductor/pc-nrfutil#134]
Hello!

I see that `pc-ble-driver` [releases 3.x](https://github.com/NordicSemiconductor/pc-ble-driver/tree/v3.0.1) support SDK v. 14. When can we expect a `nrfutil` release that supports these?

Best regards,
Łukasz

**Comment by bihanssen** [comment]
Hi, we have no immediate schedule of that. May I ask what the main reason/feature for requesting SDK 14 support is?

**Comment by LJBD** [comment]
I assume that you need SDK 14 to conduct OTAU of firmware that uses that SDK. Is it correct?

**Comment by LJBD** [comment]
All right, thank you very much!
