### ISSUE TITLE
nRF SDK 11.1 is not released

### ISSUE THREAD

**Issue by peterhinson** [NordicSemiconductor/pc-nrfutil#14]
The README states that version 1.0 (default in master) of this tool only supports nRF SDK 11.1 and later. Am I mistaken in that nRF SDK 11.0 is the latest public release?

To avoid confusion, perhaps the "modern" version should be moved to a development branch rather than master. Or specify in the README that the tool targets an unreleased version of the nRF SDK.

Thanks for your work on this!

**Comment by carlescufi** [comment]
@peterhinson apologies for the confusion. As stated  in that same README.md, if you are using SDK 11.0 you should use the 0.5.0 tagged release and not the tip of master. That said, 11.1 was a provisional name and the next version of the SDK will actually be 12.0. I will update the README.md to reflect this.
