### ISSUE TITLE
SDK 15 and Mesh 2.0 Generate a DFU file with nrfutil is NOT working

### ISSUE THREAD

**Issue by advanchip** [NordicSemiconductor/pc-nrfutil#148]
Please refer to a Public open ticket in Nordic Semiconductor DevZone:
https://devzone.nordicsemi.com/f/nordic-q-a/34782/sdk-15-and-mesh-2-0-generate-a-dfu-file-with-nrfutil---valueerror/134485#134485

We used nRF5_SDK_15.0.0_a53641a and nrf5_SDK_for_Mesh_v2.0.0_src.

We are following DFU quick start guide http://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.meshsdk.v0.10.0%2Findex.html

We started command prompt on an administrator.  I have make sure all the steps before and after step 8 using s132 softdevice version 6.0.  We tried to flash the program via both SES and nrfjprog (like shown in step 8).  We also used difference Bud rate 115200, 57600, 38400, 19200, 14400 and 9600.

Attached are the cmd script file 
[cmd scrip.txt](https://github.com/NordicSemiconductor/pc-nrfutil/files/2070309/cmd.scrip.txt)

Step 1: private_key.txt
[private_key.txt](https://github.com/NordicSemiconductor/pc-nrfutil/files/2070315/private_key.txt)

Step 2: bootloader_config_default.json

[bootloader_config_default.txt](https://github.com/NordicSemiconductor/pc-nrfutil/files/2070319/bootloader_config_default.txt)

Step 3: dfu_test.zip
[dfu_test.zip](https://github.com/NordicSemiconductor/pc-nrfutil/files/2070320/dfu_test.zip)

Step 4: Step 4: Modified devic_page_generator.py from 5.0.0 to 6.0.0 
[device_page_generator.txt](https://github.com/NordicSemiconductor/pc-nrfutil/files/2070366/device_page_generator.txt)

to generate 

 device_page_nrf52832_xxAA_s132_6.0.0.hex

[device_page_nrf52832_xxAA_s132_6.0.0.txt](https://github.com/NordicSemiconductor/pc-nrfutil/files/2070368/device_page_nrf52832_xxAA_s132_6.0.0.txt)

Step 6: s132_nrf52_6.0.0_softdevice.hex
[s132_nrf52_6.0.0_softdevice.txt](https://github.com/NordicSemiconductor/pc-nrfutil/files/2070371/s132_nrf52_6.0.0_softdevice.txt)

Step 7: mesh_bootloader_serial_armcc_nrf52832_xxAA.hex
[mesh_bootloader_serial_armcc_nrf52832_xxAA.txt](https://github.com/NordicSemiconductor/pc-nrfutil/files/2070375/mesh_bootloader_serial_armcc_nrf52832_xxAA.txt)

Step 8: Program device using nrfjprog  to download dfu_nrf52832_xxAA_s132_6.0.0.hex and dfu_nrf52832_xxAA_s132_6.0.0.map
[dfu_nrf52832_xxAA_s132_6.0.0_hex.txt](https://github.com/NordicSemiconductor/pc-nrfutil/files/2070386/dfu_nrf52832_xxAA_s132_6.0.0_hex.txt)
[dfu_nrf52832_xxAA_s132_6.0.0_map.txt](https://github.com/NordicSemiconductor/pc-nrfutil/files/2070387/dfu_nrf52832_xxAA_s132_6.0.0_map.txt)

Step 9: Program device_page_nrf52832_xxAA_s132_6.0.0.hex
[device_page_nrf52832_xxAA_s132_6.0.0.txt](https://github.com/NordicSemiconductor/pc-nrfutil/files/2070391/device_page_nrf52832_xxAA_s132_6.0.0.txt)

Step 10: We used COMPORT (COM46) 
![com port](https://user-images.githubusercontent.com/32427304/40948417-335cad9e-681d-11e8-83a1-065192597557.PNG)

and tried difference Baud Rates, press Button 4 and RESET and release both to enter DFU mode and use s132 and version 6.0.0, still got

"Error is: Failed to establish connection"

Please advise.  Thanks.

**Comment by bihanssen** [comment]
Closing this issue as it is being follow up on [devzone](https://devzone.nordicsemi.com/f/nordic-q-a/34782/sdk-15-and-mesh-2-0-generate-a-dfu-file-with-nrfutil---valueerror/134485#134485).
