### ISSUE TITLE
Is it possible to include the application version in the manifest.json so that the iOS app can read it?

### ISSUE THREAD

**Issue by jin-khera-eastpoint** [NordicSemiconductor/pc-nrfutil#159]
We would like to get the application(firmware) version from the DFU package and use it within the iOS app. The reason being we would like to know beforehand what the version is before running the DFU process.

**Comment by bihanssen** [comment]
@jin-khera-eastpoint we will look into the matter and come back with more info.

**Comment by bihanssen** [comment]
This issue has not been prioritized, however you are welcome to create a PR for it.
