### ISSUE TITLE
No Key File Failure

### ISSUE THREAD

**Issue by djlitvak** [NordicSemiconductor/pc-nrfutil#16]
When I run nrfutil dfu genpkg and do not feed a key file, the python crashes at line 238 of dfu/package.py with "AttributeError: 'Package' object has no attribute 'key_file'" on the line that reads "signer.load_key(self.key_file)"

Please advise!

**Comment by carlescufi** [comment]
Are you running the 0.5.1 tag? Master is not compatible with SDK 11.0 and SDK 12.0 is not yet out

**Comment by djlitvak** [comment]
Got it - no I was running on Master. I downgraded to 0.3 and things are working much better.
