### ISSUE TITLE
ImportError: cannot import name config while trying dfu on thread

### ISSUE THREAD

**Issue by tarunsmalviya** [NordicSemiconductor/pc-nrfutil#164]
I had installed nrfutil in RPi3B and trying to run **nrfutil dfu thread -pkg app_dfu_package.zip -p /dev/ttyACM0** command.

I am getting following error:
![screen shot 2018-09-25 at 3 27 47 pm](https://user-images.githubusercontent.com/9993036/46009632-cd54eb00-c0dd-11e8-90e4-dd42a9214602.png)

Please help me

**Comment by bihanssen** [comment]
Hi, 
it seems that it is missing `config` from the `pc-ble-driver-py` dependency.
RPi is not officially supported by nrfutil. How did you install nrfutil and it's dependencies?

**Comment by bihanssen** [comment]
Closing as won't fix. RPi is not officially supported.
