### ISSUE TITLE
Suppress giant warning?

### ISSUE THREAD

**Issue by jimparis** [NordicSemiconductor/pc-nrfutil#170]
The new warning added by 1348f912 seems overly obnoxious.  I am targetting SDK 15.1 and therefore do want the backup page, but there appears to be no way to disable this huge 15 line warning in my build output every time.  Can it be toned down a bit?

**Comment by bihanssen** [comment]
Hi, I see your point regarding the warning. We will consider how it could be modified. If you have a suggestion you could add it in a PR.
Thanks.

**Comment by jimparis** [comment]
Sure, I added a PR, although really this warning should disappear entirely at some point.  Maybe nrfutil should be passed an option specifying which SDK version it should target, and then it can make these sorts of decisions automatically.

**Comment by bihanssen** [comment]
Thanks, I added your suggestion about specifying SDK version to our backlog for evaluation.
