### ISSUE TITLE
Message for address format for nrfutil dfu ble -a

### ISSUE THREAD

**Issue by sijohans** [NordicSemiconductor/pc-nrfutil#174]
Hello,

I'm trying to perform an upgrade using nrfutil. My device does not advertise any device name so i need to specify the address. If running with verbose i can se my device in the advertising report:
```
2018-11-05 13:52:58,848 Received advertisement report, address: 6CE9AC65A836, device_name: 
 peer_addr(68:33:75:EB:11:73)
```
Of course i tried to use **-a 68:33:75:EB:11:73** and not **-a 683375EB1173**. This took me some while to find, would be nice if the application could give a message regarfing the format, or if the format could be printed in the help.

**Comment by bihanssen** [comment]
Thanks for reporting.
