### ISSUE TITLE
How to perform dfu using existing Californium CoAP server instead of NCP?

### ISSUE THREAD

**Issue by tarunsmalviya** [NordicSemiconductor/pc-nrfutil#176]
To perform dfu using nrfutil, we need to bring wpantund service down in order to provide serial port to nrfutil. That restrict me to communicate with end nodes. Can you please help, how we can do dfu using the coap server running in RPi and without stopping wpantund service.

**Comment by tarunsmalviya** [comment]
I found one solution by reviewing code, i.e., using socket connection in NCPTransport "S:5683". But I am getting connection refused error.

**Comment by bihanssen** [comment]
Hi @tarunsmalviya 
as this is more of a usage question I will kindly ask you to re-post on [DevZone](https://devzone.nordicsemi.com).
