### ISSUE TITLE
dfu command incorrectly says 1M connectivity is firmware as correct when 115200 is required

### ISSUE THREAD

**Issue by mikebwilliams** [NordicSemiconductor/pc-nrfutil#179]
https://github.com/NordicSemiconductor/pc-nrfutil/issues/48

**Comment by bihanssen** [comment]
Correct, the firmware checking is not checking baud rate. This could be improved.

**Comment by halkver** [comment]
Works as intended, the baud rate is correctly checked when the "-f" flag is given.
