### ISSUE TITLE
Event disconnect always falsely triggered after connection

### ISSUE THREAD

**Issue by mikebwilliams** [NordicSemiconductor/pc-nrfutil#180]
https://github.com/NordicSemiconductor/pc-nrfutil/blob/a305f5a8ec7bc2deda91829cdf7ac18e7f48217b/nordicsemi/dfu/dfu_transport_ble.py#L226

This event always falsely occurs upon the 1 second timeout after connection using nrfutil 4.0.0 on Ubuntu 18.04 using the 115.2Kbps connectivity firmware on PCA10040 causing nrfutil to think the device has disconnected when it hasn't. Inserting a break after the if block to  ignore the "disconnect"  makes the connection work. Verified using wireshark / device RTT output log.

**Comment by kenr** [comment]
Hi! We do not have capacity to maintain and release new versions of this utility.
We have made a new utility with the same name and feature set. It can be found here: https://www.nordicsemi.com/Products/Development-tools/nrf-util
