### ISSUE TITLE
pip package

### ISSUE THREAD

**Issue by samueldotj** [NordicSemiconductor/pc-nrfutil#2]
It would be great if this is available as standard pip package?
Any plan of doing that?

**Comment by ndahlquist** [comment]
As a workaround, note that you can install this using pip like this:

```
pip install git+https://github.com/NordicSemiconductor/pc-nrfutil.git
```

(you can also add this to a requirements.txt file, which is nice)

**Comment by carlescufi** [comment]
This will come very soon

**Comment by carlescufi** [comment]
Fixed in master, but only for the modern DFU version. New SDK with support for  it coming very soon
