### ISSUE TITLE
When running on W10 I get:  The 'antlib~=1.0b' distribution was not found and is required by nrfutil

### ISSUE THREAD

**Issue by mmonson** [NordicSemiconductor/pc-nrfutil#210]
I just pulled commit 1d20b11  and installed it on Windows 10 Pro Version 1809 
When I run nrfutil --help I get this error: 

File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'antlib~=1.0b' distribution was not found and is required by nrfutil

**Comment by cchengVA** [comment]
FYI - make sure you're running a 32bit version of Python... we hit the same issue just now and that is what's fixing it.

**Comment by bihanssen** [comment]
@mmonson thanks for reporting. Are you running 32 or 64 bit version of Python? 
For reproduction, can you describe how you install nrfutil after pulling the commit?
