### ISSUE TITLE
running "pip install nrfutil" I get this message "Could not find a version that satisfies the requirement antlib~=1.0b (from nrfutil) 

### ISSUE THREAD

**Issue by HLilit** [NordicSemiconductor/pc-nrfutil#213]
When running "pip install nrfutil" I get this message - 
 "Could not find a version that satisfies the requirement antlib~=1.0b (from nrfutil) (from versions: ) No matching distribution found for antlib~=1.0b (from nrfutil)"

Windows 10
Python 2.7.16
setuptools are already up-to-date

**Comment by bihanssen** [comment]
nrfutil does not support 64 bit python currently, please try with 32 bit python.
We will look into providing a better error message for the issue.

**Comment by HLilit** [comment]
Thanks, I will try with 32 bit python.
