### ISSUE TITLE
VirusTotal warnings!

### ISSUE THREAD

**Issue by E3V3A** [NordicSemiconductor/pc-nrfutil#219]
Uploading the latest release 5.1.0 for Windows, gives a number of hits with VT. 
I'm not sure what package mechanism you're using or if your dev machine is infected, but that is never a good sign. 

![firefox_2019-03-26_22-48-10](https://user-images.githubusercontent.com/194392/55032776-8eaad980-5009-11e9-84ed-deb33748606f.png)

**Comment by E3V3A** [comment]
May alse be related to unsolved (?) issue in different repo:
* https://github.com/NordicSemiconductor/pc-nrfconnect-core/issues/253

**Comment by bihanssen** [comment]
We have tested the application and build machines with our AV tools and haven't found any indications on there being any real findings. We therefore consider the VirusTotal hits to be false positives. Closing the issue.
