### ISSUE TITLE
Flashing bootloader into nrf52832

### ISSUE THREAD

**Issue by kungfupizza** [NordicSemiconductor/pc-nrfutil#233]
Hi,
I have a STM32 based JTAG connector with SWD connectivity. I have connected this to the nrf52832 board but having these errors with nrfutil
![image](https://user-images.githubusercontent.com/46355685/60755401-8a6e5f00-9fef-11e9-98d0-dd372b915a75.png)

**Comment by bihanssen** [comment]
Hi,
please post this issue on DevZone for follow up from Nordic tech support.
