### ISSUE TITLE
Fatal Python error: PyThreadState_Get: no current thread Abort trap: 6

### ISSUE THREAD

**Issue by acrepinheroux** [NordicSemiconductor/pc-nrfutil#24]
using python 2.7.11, running OS X El Capitan 10.11.4.

**Comment by carlescufi** [comment]
pypi install, master or the 0.5.1 release?

**Comment by carlescufi** [comment]
also could you please specify what command-line options you used to trigger the error?

**Comment by acrepinheroux** [comment]
Master. Any command, nrfutil --help will make it crash. How do I run the 0.5.1 release?

**Comment by acrepinheroux** [comment]
That's my bad. 0.5.1 works fine. Thank you
