### ISSUE TITLE
Issue running on OS X on El-Capitan with python2.7

### ISSUE THREAD

**Issue by vrahane** [NordicSemiconductor/pc-nrfutil#27]
```
Vipuls-MacBook-Pro:pc-nrfutil vipul$ nrfutil keys generate private.pem
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6

Vipuls-MacBook-Pro:pc-nrfutil vipul$ python
Python 2.7.11 (default, Jan 22 2016, 08:29:18) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by carlescufi** [comment]
Did you install with pip?

**Comment by carlescufi** [comment]
Also, are you running the built-in OS X Python or a Homebrew one? Try:

`$ which python`

**Comment by vrahane** [comment]
Yes, I did.
`Vipuls-MacBook-Pro:myproj vipul$ pip -V
pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)`

**Comment by carlescufi** [comment]
This could be a library problem. Can you give me the ouput of:

`otool -L /Library/Python/2.7/site-packages/pc_ble_driver_py/lib/macos_osx/_pc_ble_driver.so`
and
`otool -L /Library/Python/2.7/site-packages/pc_ble_driver_py/lib/macos_osx/libpc_ble_driver_shared.dylib`

?

**Comment by vrahane** [comment]
```
Vipuls-MacBook-Pro:myproj vipul$ otool -L /Library/Python/2.7/site-packages/pc_ble_driver_py/lib/macos_osx/_pc_ble_driver.so
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: can't open file: /Library/Python/2.7/site-packages/pc_ble_driver_py/lib/macos_osx/_pc_ble_driver.so (No such file or directory)
```

and

```
Vipuls-MacBook-Pro:myproj vipul$ otool -L /Library/Python/2.7/site-packages/pc_ble_driver_py/lib/macos_osx/libpc_ble_driver_shared.dylib
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: can't open file: /Library/Python/2.7/site-packages/pc_ble_driver_py/lib/macos_osx/libpc_ble_driver_shared.dylib (No such file or directory)
```

**Comment by carlescufi** [comment]
Oh right I see, your python libs are in /usr/local/lib so you're using Homebrew's Python. Not sure why, but apparently you need to use the default OS X python build for our libs to work. 

You can simply edit `/etc/paths` to put `/usr/bin` before `/usr/local/bin` then install again with pip (but using the default python and not homebrew's).

**Comment by carlescufi** [comment]
More info about switching between Hombrew's Python and the default OS X Python can be found [here](http://stackoverflow.com/questions/5157678/python-homebrew-by-default)

**Comment by vrahane** [comment]
Sure, I will try it out and let you know. Thank you.

**Comment by vrahane** [comment]
So, I had to do a bunch of things but it worked finally. I had to reinstall pip and nrfutil after removing brew installed python. Thank you so much for your help.

**Comment by carlescufi** [comment]
No prob, thanks for reporting it. I'll see if I can add this to the doc.

**Comment by vikeri** [comment]
Getting the same issue, using the built in macOS Python is not an alternative for me unfortunately. This only occurs when I run `nrfutil dfu ble` it works as expected when I run `nrfutil pkg generate`.
