### ISSUE TITLE
Package contains old intelhex files

### ISSUE THREAD

**Issue by nrbrook** [NordicSemiconductor/pc-nrfutil#281]
The 5.2.0 package on PyPI contains some intelhex files from version 1.5:

https://files.pythonhosted.org/packages/95/bd/c69458ec1b9f66b5874bcf7df60f4e768b5fa137663637241628bfdea135/nrfutil-5.2.0.tar.gz

This prevents it working on python 3.

https://devzone.nordicsemi.com/f/nordic-q-a/54525/nrfutil-does-not-work-with-python-3-for-generating-bootloader-settings-page

**Comment by nrbrook** [comment]
I see this is fixed in 6.0.0. When will this be released?

**Comment by bihanssen** [comment]
nrfutil is currently available as pre-release v6.0a. A final release v6 will be made soon.
