### ISSUE TITLE
Sending multi-image DFU over serial fails due to incorrect packet sequence

### ISSUE THREAD

**Issue by ACGarland** [NordicSemiconductor/pc-nrfutil#29]
I've been testing serial DFU with an customized version from branch 0.5.1 which supports recording the packet output stream. It appears there may be a defect related to packet sequence numbering for the case where the DFU ZIP file used for the DFU update contains more than one image.

For example, if nrfutil is first used to build a DFU ZIP file containing bootloader, softdevice, and application, then the resulting file contains two images: 1) a BL+SD image, and 2) an APP image.

If this same DFU ZIP file is provided to nrfutil to initiate a serial DFU, the serial transport does not reset the packet sequence number between sending the two images. This results in a somewhat "random" staring sequence number for the second image (depending on how many packets are in the first image modulus 8). In my case, I was producing two HCI packet recording files which I then replay to a serial bootloader, but the second one never was accepted correctly since it didn't begin with sequence 1. I corrected the problem by setting the HCiPacket.sequence_number = 0 within the serial transport open() function. (Maybe close would have been a better location, I'm not sure.) In any case, that produced two recording files where both of them have sequence 1 for the first packet and that seems to work.

**Comment by bihanssen** [comment]
The new serial DFU in master (non-legacy) does not use packet sequence number and so does not have the issue described here. Closing this issue.
