### ISSUE TITLE
nrfutil 6.0.0 cannot be installed with Python 3.8.1 on Windows

### ISSUE THREAD

**Issue by carlescufi** [NordicSemiconductor/pc-nrfutil#291]
When installing nrfutil with Python 3.8.1 on Windows, `pip3` pulls down nrfutil 5.2.0 instead of 6.0.0.

This was tested with both:

- pip3 19.2.3 (Python 3.8.1 64-bit)
- pip3 19.3.1 (Python 3.8.1 64-bit)

**Comment by bihanssen** [comment]
Fixed with #292, released in v6.0.1
