### ISSUE TITLE
Silent "Zip created at" message

### ISSUE THREAD

**Issue by samueldotj** [NordicSemiconductor/pc-nrfutil#3]
I am not sure of use of this message - the filename is already known to the user.
When using the tool with parallel makefiles getting this message does not make sense.

Although it is easy to disable it by redirecting the output to /dev/null, it would be good to get it fixed in the tool itself.

Is it possible to show this message only if --verbose is specified.
Another option is --silent to suppress this message.

If needed I can submit a patch.

**Comment by carlescufi** [comment]
So no feedback at all by default? I think that could be confusing to users

**Comment by carlescufi** [comment]
Closing for now, reopen if you want the feature or send a pull request.
