### ISSUE TITLE
Support for python 3.9

### ISSUE THREAD

**Issue by nrbrook** [NordicSemiconductor/pc-nrfutil#334]
Please add support for python 3.9! When installing with pip 3.9, an old version of nrfutil is used because 6.1.0 only supports <3.9. But other Nordic tools (nrfjprog.py in nRF mesh SDK) need 3.9 and won't work with 3.8.

**Comment by bihanssen** [comment]
@nrbrook Python 3.9 support is targeted for next release, though it not clear exactly when that will be.
