### ISSUE TITLE
python 3.9 / pip 20.3.1 installs 5.2.0 instead of 6.1.0 on macos

### ISSUE THREAD

**Issue by myst729** [NordicSemiconductor/pc-nrfutil#336]
Even if with `--no-cache-dir`.

**Comment by libcg** [comment]
Same issue on Arch Linux with `pip3`.

**Comment by libcg** [comment]
Fixed it by running the following command after `pip3 install nrfutil` (Arch only):
`# pip3 install --no-deps -t /usr/lib/python3.9/site-packages --python-version 3.8 --ignore-requires-python --upgrade nrfutil`

**Comment by myst729** [comment]
Workaround here: https://github.com/ferrous-systems/embedded-trainings-2020/pull/115/

**Comment by bihanssen** [comment]
Thanks for the info @libcg. I suspect you might run into problems if running commands that actually require ble-driver-py, like DFU over BLE.
Install fails because ble-driver-py does not yet include wheels for python versions other than 3.6-3.8.

**Comment by myst729** [comment]
> Thanks for the info @libcg. I suspect you might run into problems if running commands that actually require ble-driver-py, like DFU over BLE.
> Install fails because ble-driver-py does not yet include wheels for python versions other than 3.6-3.8.

I did. So it looks like nrfutil is waiting for *ble-driver-py* to be compatible with python 3.9

**Comment by chrysn** [comment]
If there are dependencies that have a habit of breaking with compatible Python versions, could they become optional? There is the "extras" mechanism that'd allow just that.

**Comment by bihanssen** [comment]
@chrysn that would be useful. Have tried similar in the past without success. If you have a PR to demonstrate that would be helpful.

**Comment by chrysn** [comment]
Sorry, can't help with a PR here for policy reasons (as this module is not published under an OSI-approved license).

**Comment by gelintonx** [comment]
Same problem with Parrot Os and Python 3.9, I had to downgrade to python 8 to get the latest version

**Comment by myst729** [comment]
6.1.2 works
