### ISSUE TITLE
Installation fails: ImportError: No module named setuptools_behave

### ISSUE THREAD

**Issue by NanaDada** [NordicSemiconductor/pc-nrfutil#339]
Calling `sudo python setup.py install` (on Ubuntu) fails with:
```
Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    from setuptools_behave import behave_test
ImportError: No module named setuptools_behave

```
Do you have any ideas how to fix this?

**Comment by bihanssen** [comment]
@NanaDada, maybe if you try to install requirements-dev with `pip install -r requirements-dev.txt` first, as it includes the `behave`module.

**Comment by kenr** [comment]
Hi! We do not have capacity to maintain and release new versions of this utility.
We have made a new utility with the same name and feature set. It can be found here: https://www.nordicsemi.com/Products/Development-tools/nrf-util
