### ISSUE TITLE
nrfutil_v6.1.0 should use connectivity firmware v4.1.2 for usb dongle

### ISSUE THREAD

**Issue by xiaoshideyuxiang** [NordicSemiconductor/pc-nrfutil#341]
nrfutil_v6.1.0 should use connectivity firmware v4.1.2(fixed some fatal bug)

https://github.com/NordicSemiconductor/pc-nrfutil/blame/v6.1/nordicsemi/__main__.py#L1177

`
            connectivity_firmware = os.path.join(
                                        os.path.dirname(config.__file__),
                                        "hex",
                                        "sd_api_v5",
                                        "connectivity_4.1.1_usb_with_s132_5.1.0_dfu_pkg.zip"
                                    )
`

after manual change code  to 

`
            connectivity_firmware = os.path.join(
                                        os.path.dirname(config.__file__),
                                        "hex",
                                        "sd_api_v5",
                                        "connectivity_4.1.2_usb_with_s132_5.1.0_dfu_pkg.zip"
                                    )
`

Test nrfutil with PCA10059 usb dongle, download connectivity firmware successful(via cmd "nrfutil dfu ble ...-f")

However there are still some errors when i try to use it to dfu a target board(pca10040), will rise Exception:("Failure-Connection failed due to 0x3e")

**Comment by bihanssen** [comment]
@xiaoshideyuxiang, nrfutil will in next release be updated to point to the latest ble-driver-py, v0.15.0. which carries the 4.1.2 firmware.
I am not sure why you are receving the 0x3e error though, I don't suspect that is related to the firmware version. You can lookup articles on 0x3e on devzone for more info on that error message.
