### ISSUE TITLE
nrfutil APPCRASH (0xc0000005) with latest libusb1, not specified in requirements.txt

### ISSUE THREAD

**Issue by ShannonGreen** [NordicSemiconductor/pc-nrfutil#351]
There seems to be a problem using pip-installed nrfutil with the latest version of libusb1 in pypi (1.9.2)

When running 
```
 nrfutil dfu usb-serial -p COM18 -pkg connectivity_4.1.2_usb_with_s132_5.1.0_dfu_pkg.zip
```
I get random crashes of the Python process with exit code 0xc0000005 (access violation) - probably at least 50% of the time. 

requirements.txt does not specify a version for libusb1 but requirements-frozen.txt does specify 1.7.1, which works. 

I notice there is a libusb.dll committed into the repo, but this won't be used if you install the package with pip. I can't tell what version that is, though? 

This took me quite a lot of debugging to figure out. If the expectation is to install libusb1 with pip, then the repo binary should probably be removed and the requirements for the pypi package updated.

**Comment by kenr** [comment]
Hi! We do not have capacity to maintain and release new versions of this utility.
We have made a new utility with the same name and feature set. It can be found here: https://www.nordicsemi.com/Products/Development-tools/nrf-util

The SoftDevice v6.X and higher will not be supported in this utility or the new one with the same name.
