### ISSUE TITLE
Mac M1 support: temporary solution

### ISSUE THREAD

**Issue by paulrouget** [NordicSemiconductor/pc-nrfutil#361]
For anyone else who's been struggling installing nrfutil for M1, clone [this fork](https://github.com/iamfat/pc-nrfutil) and just `pip install .`.

**Comment by timsterc** [comment]
Upgraded to a MB Air w/ an M1 - and my build scripts are now throwing an error:

```
  File "/Users/timsterc/miniforge3/envs/py38/lib/python3.8/site-packages/nordicsemi/__main__.py", line 805, in generate
    sd_req_list += set(sd_id_list) - set(sd_req_list)
TypeError: unsupported operand type(s) for +=: 'map' and 'set'
```

Just curious of the above mentioned fix might resolve this, or if it's a Python version error?

I've installed the latest (6.1.3) nrfutil via pip ... and have tried numerous Python versions (3.8.6, 3.8.12, 3.9.9 ... all result in the same error.

**Comment by ShaharHD** [comment]
I've created https://github.com/NordicSemiconductor/pc-ble-driver/pull/271 which should allow to properly do this on a M1 mac or any ARM based OS/device

**Comment by wiesener** [comment]
Sorry but will the be fixed inside normal master branch aswell?

**Comment by StephaneJuban** [comment]
@ShaharHD I am following your steps to build `pc-ble-driver` but when I run `cmake --build .` I got : 

> ninja: error: loading 'build.ninja': No such file or directory

```
$ ninja --version
1.10.2

$ cmake --version
cmake version 3.23.0
```

**Comment by kenr** [comment]
Hi! We do not have capacity to maintain and release new versions of this utility.
We have made a new utility with the same name and feature set. It can be found here: https://www.nordicsemi.com/Products/Development-tools/nrf-util
