### ISSUE TITLE
No matching distribution found for pc_ble_driver_py>=0.16.1 

### ISSUE THREAD

**Issue by ohadshapira** [NordicSemiconductor/pc-nrfutil#367]
No version 0.16.1 in pc_ble_driver_py. Latest release is 0.16.2
https://github.com/NordicSemiconductor/pc-ble-driver-py/branches

**Comment by kenr** [comment]
Hi! We do not have capacity to maintain and release new versions of this utility.
We have made a new utility with the same name and feature set. It can be found here: https://www.nordicsemi.com/Products/Development-tools/nrf-util
