### ISSUE TITLE
Tests missing from sdist tarball on pypi.org

### ISSUE THREAD

**Issue by dvzrv** [NordicSemiconductor/pc-nrfutil#385]
Hi! I'm packaging this project for Arch Linux. We usually run tests included in upstream projects to ensure integration with our Python ecosystem and rely on sdist tarballs from pypi.org if possible.
Unfortunately the sdist tarballs on pypi.org do not include the tests and test data required to run any tests. It would be great if you could add them! :)

**Comment by kenr** [comment]
Hi! We do not have capacity to maintain and release new versions of this utility.
A new utility with the same name and feature set is made. It can be found here: https://www.nordicsemi.com/Products/Development-tools/nrf-util
