### ISSUE TITLE
6.1.6: requirements.txt is installed to site-packages

### ISSUE THREAD

**Issue by dvzrv** [NordicSemiconductor/pc-nrfutil#386]
Hi! I package this project for Arch Linux. I noticed that the requirement.txt of this project is added top-level to the site-packages directory upon installation. This should not be done, as that file is not required during runtime and should not end up on the user's system.

**Comment by kenr** [comment]
Hi! We do not have capacity to maintain and release new versions of this utility.
A new utility with the same name and feature set is made. It can be found here: https://www.nordicsemi.com/Products/Development-tools/nrf-util
