### ISSUE TITLE
6.1.6: Vendoring unneeded precompiled files

### ISSUE THREAD

**Issue by dvzrv** [NordicSemiconductor/pc-nrfutil#387]
Hi! I package this project for Arch Linux. Upon installation I noticed, that precompiled libusb libraries are installed to site-packages, which I have to remove manually.
Please rely upon https://pypi.org/project/libusb/ (which can be built from source) instead of vendoring precompiled files, as they can not be verified and are on top also installed for architectures that do not require them.

**Comment by kenr** [comment]
Hi! We do not have capacity to maintain and release new versions of this utility.
A new utility with the same name and feature set is made. It can be found here: https://www.nordicsemi.com/Products/Development-tools/nrf-util
