### ISSUE TITLE
Feature request - include nrfutil executable for windows users

### ISSUE THREAD

**Issue by vidarbe** [NordicSemiconductor/pc-nrfutil#39]
Please refer to this [thread](https://devzone.nordicsemi.com/question/106083/request-for-nrfutil-windows-executable/) on the forum. It lists up some valid points on why it would be nice to have nrfutil.exe included in the release.

**Comment by bihanssen** [comment]
Thanks for the feedback. I've added it to the backlog, though it's not clear when it will happen.

**Comment by bihanssen** [comment]
A precompiled .exe version of nrfutil has been made available on [github releases page](https://github.com/NordicSemiconductor/pc-nrfutil/releases).
