### ISSUE TITLE
Update SoftDevice firmware IDs

### ISSUE THREAD

**Issue by MalinKildal** [NordicSemiconductor/pc-nrfutil#45]
The list of SoftDevice firmware IDs is not up to date. This information is required when working with DFU.
The list currently looks like this: 
|s130_nrf51_1.0.0|0x67|
|s130_nrf51_2.0.0|0x80|
|s132_nrf52_2.0.0|0x81|
|s130_nrf51_2.0.1|0x87|
|s132_nrf52_2.0.1|0x88|
|s132_nrf52_3.0.0|0x8C|

**Comment by bihanssen** [comment]
Thanks for the update. Could you submit a PR for this?
