### ISSUE TITLE
PIP installs ancient version

### ISSUE THREAD

**Issue by lcrocker** [NordicSemiconductor/pc-nrfutil#47]
On my Ubuntu (Xenial) box, "pip install nrfutil" installs version 0.3.0.

**Comment by bihanssen** [comment]
Hi! I'm not sure why pip would install an older version. Have you tried upgrading with `pip install nrfutil -U`?

**Comment by bihanssen** [comment]
Hi, do you still see an issue with the version?

**Comment by bihanssen** [comment]
Closing the, please reopen if still valid.
