### ISSUE TITLE
Update README.md to state what version of Protobuf is used.

### ISSUE THREAD

**Issue by hakonfam** [NordicSemiconductor/pc-nrfutil#49]
I'm not certain if PB2 and PB3 (the used versions) are compatible, if they are, it should be stated. If they are not, it should be stated explicitly which version should be used.

I think its PB2 due to the name of the generated file "dfu_cc_pb2.py".

**Comment by bihanssen** [comment]
protobuf v3 is able to generate both proto2 and proto3 language versions, meaning that installing the latest version of protobuf is ok. It is however important that proto2 language is generated, which is specified in the .proto file by *not* including `syntax = "proto3"`.

**Comment by bihanssen** [comment]
The README has been updated with info on language versions.
