### ISSUE TITLE
Users needs to use kill -9 to kill the process

### ISSUE THREAD

**Issue by Martinsbl** [NordicSemiconductor/pc-nrfutil#5]
When using pc-nrfutil for dfu update and running on linux: 
After dfu finished, in case of exception, or error nrfutil continue running users needs to use kill -9 to kill the process.

**Comment by daviddedwin** [comment]
+1

**Comment by kenr** [comment]
Hi,

I'm not able reproduce this; I'm running on Ubuntu 15.10. What environment do you have nrfutil running in ? 

Closing the issue, please feel free to reopen the issue if you are still experiencing this issue and have more data on how to reproduce.
