### ISSUE TITLE
Doc: "Hardware setup" link broken

### ISSUE THREAD

**Issue by charleswhchan** [NordicSemiconductor/pc-nrfutil#53]
The "Hardware setup" link in README does not work:

> Note: To use the dfu ble option you will need to set up your boards to be able to communicate with your computer. You can find additional information here: [Hardware setup](https://github.com/NordicSemiconductor/pc-ble-driver/tree/self_contained_driver#hardware-setup).

**Comment by bihanssen** [comment]
Thanks for reporting. Fixed in 8a3be3e.

**Comment by charleswhchan** [comment]
Thanks!
