### ISSUE TITLE
pyinstaller issues

### ISSUE THREAD

**Issue by mikebwilliams** [NordicSemiconductor/pc-nrfutil#54]
nrtutils.spec, line 14:
Master uses \\ instead of / in two places, which causes the search for nodicsemi/__main__.py to fail on linux.

Also, pyinstaller fails unless the whole path to nrfutils.spec is given, not just the relative path. So the instructions should show:
pyinstaller /whole/path/here/nrfutils.spec

**Comment by bihanssen** [comment]
Thanks for the report.
