### ISSUE TITLE
Upload version 0.5.2 of nrfutil to PyPI

### ISSUE THREAD

**Issue by seppestas** [NordicSemiconductor/pc-nrfutil#65]
As [stated in the README](NordicSemiconductor/pc-nrfutil#versions) version 0.5.2 of this tool needs to be installed in order to build packages for the legacy DFU system. However, the latest version <= version 0.5.2 that can installed using pip is [version 0.3.0]( https://pypi.python.org/pypi/nrfutil/0.3.0).

Since [mbed-os](https://github.com/ARMmbed/mbed-os) still comes with the legacy DFU bootloader I think a lot of people (including me) still use the legacy DFU package format. It would be nice if a more recent version (i.e version 0.5.2) of the tool that supports the legacy DFU package format could be installed using pip.

**Comment by bihanssen** [comment]
Version 0.5.2 of nrfutil has been uploaded to [pypi](https://pypi.python.org/pypi?%3Aaction=pkg_edit&name=nrfutil). Please report if any issues.

Thanks.
