### ISSUE TITLE
Installing version 0.5.2 does not install requirements

### ISSUE THREAD

**Issue by seppestas** [NordicSemiconductor/pc-nrfutil#76]
When installing nrfutil 0.5.2 using
```
pip install nrfutil==0.5.2
```
the requirements listed in [requirements.txt](https://github.com/NordicSemiconductor/pc-nrfutil/blob/v0.5.2/requirements.txt) do not get installed. This is because [setup.py](https://github.com/NordicSemiconductor/pc-nrfutil/blob/v0.5.2/setup.py) does not seem to install them.

Related to issue #65.

**Comment by bencefr** [comment]
Until we provide a solution, could you install 2.3.0 first, then revert to 0.5.2, so requirements will be met?
```
pip install nrfutil==2.3.0
pip install nrfutil==0.5.2
```

**Comment by seppestas** [comment]
Currently we just install the requirements directly, which seems to work:
```
pip install pyserial>=2.7 enum34>=1.0.4 click==5.1 ecdsa>=0.13
```

The method you described works as well, but is a bit less efficient since it requires nrfutil 2.3.0 to be downloaded, installed and uninstalled, and it is a bit less "maintainable" since the versions of the requirements required by later versions of nrfutil might be different from the versions required by nrfutil 0.5.2.

**Comment by mrodem** [comment]
This issue was fixed by 799dd919, which was released with 0.5.3.

**Comment by seppestas** [comment]
@mrodem @bihanssen Could you also release it on PyPI?

**Comment by mrodem** [comment]
@seppestas Check now.

**Comment by seppestas** [comment]
Works, thanks 👍
