### ISSUE TITLE
Can not install nrfutil v3.0.0 from pip install

### ISSUE THREAD

**Issue by qung** [NordicSemiconductor/pc-nrfutil#80]
Got this error:
Downloading/unpacking pyspinel (from nrfutil==3.0.0)
  Could not find a version that satisfies the requirement pyspinel (from nrfutil==3.0.0) (from versions: 1.0.0a1)

**Comment by bencefr** [comment]
Please update your python installation to 2.7.10+

**Comment by mrodem** [comment]
Solution proposed, and no further comments from user. Closing the issue.
