### ISSUE TITLE
Serial DFU pinging fails if bootloader is not ready

### ISSUE THREAD

**Issue by magnev** [NordicSemiconductor/pc-nrfutil#84]
Serial DFU could fail if bootloader board is not ready when trying to ping. This could happen during a combined DFU.

In dfu_transport_serial.py in open() the bootloader board is pinged twice.
If the first __ping() fails the complete DFU operation fails. It looks like the first __ping() should be removed.

Also, when looking into the __ping() function, I see that instead of returning an error code, it will raise an exception when the bootloader board is not responding. This will break the "waiting for ping"-functionality in open().

**Comment by mrodem** [comment]
Fix included in v3.2.1 release.
