### ISSUE TITLE
ImportError: No module named nordicsemi.thread.dfu_server

### ISSUE THREAD

**Issue by idelsink** [NordicSemiconductor/pc-nrfutil#85]
When I run the the nrfutil application without nrfutil installed I get the following error:

```sh
$ python nordicsemi/__main__.py
Traceback (most recent call last):
  File "nordicsemi/__main__.py", line 39, in <module>
    from nordicsemi.thread.dfu_server import ThreadDfuServer
ImportError: No module named nordicsemi.thread.dfu_server
```
This doesn't happen when I have nrfutil installed on the system. (I guess it that uses the installed files?)

## Setup

- Python: 2.7
- OS: GNU/Linux - Fedora 26
- Latest master checkout (2de577f252be42f7a3037a924158302ef7d75834)

## Steps to reproduce

- Make sure nrfutil is **not** installed on the system (Global or local)
- run `python nordicsemi/__main__.py` in the root of the pc-nrutil repo

**Comment by mrodem** [comment]
Fixed in #86.
